import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img alt="alt text here" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <h1>Main Page</h1>
        <div>
          {data.map((item) => {
            return (
              <a key={item.id} href={`/events/${item.id}`}>
                <Image
                  width={200}
                  height={100}
                  src={item.image}
                  alt={item.title}
                />
                <h2>{item.title}</h2>
                <p>{item.description}</p>
              </a>
            );
          })}
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </>
  );
}
// Server Side Rendering
export async function getServerSideProps() {
  const { events_categories } = await import("./data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}

// Client Side Rendering
// export async function getStaticProps() {
//   const { events_categories } = await import("./data/data.json");
//   return {
//     props: {
//       data: events_categories,
//     },
//   };
// }
