import Head from "next/head";
import { Inter } from "@next/font/google";
import HomePage from "@/src/components/home/HomePage";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
}
// Server Side Rendering
export async function getServerSideProps() {
  const { events_categories } = await import("./data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}

// Client Side Rendering
// export async function getStaticProps() {
//   const { events_categories } = await import("./data/data.json");
//   return {
//     props: {
//       data: events_categories,
//     },
//   };
// }
