import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import HomePage from "@/src/home/home-page";
import Footer from "@/src/footer/footer";
import Header from "@/src/header/header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomePage data={data} />
      <Footer />
    </>
  );
}
// Server Side Rendering
export async function getServerSideProps() {
  const { events_categories } = await import("./data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}

// Client Side Rendering
// export async function getStaticProps() {
//   const { events_categories } = await import("./data/data.json");
//   return {
//     props: {
//       data: events_categories,
//     },
//   };
// }
